### ISSUE TITLE
spotify-clone

### ISSUE THREAD

**Issue by Deepasha1406** [avinash3005/Hacktoberfest2024_avi_1#3]
Hey @avinash3005, As a beginner in open source can I contribute by adding spotify clone.

**Comment by avinash3005** [comment]
@Deepasha1406 sure. please do it.

**Comment by Deepasha1406** [comment]
Thank you

**Comment by Deepasha1406** [comment]
hey @avinash3005, I can't able to access your repository.
Can you please invite me as a Collaborator, So i can contribute on your page.

**Comment by avinash3005** [comment]
ok

**Comment by avinash3005** [comment]
Closing the issue now. I hope everything addressed. Can you see this counted in your progress report.
@Deepasha1406

**Comment by avinash3005** [comment]
Closing it now.
